#!/bin/bash
namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
if [ -z $namespace ];then
    exit 1
fi
/resalloc-kubernetes add --image-tag ${BUILDER_SHA256} \
    --namespace $namespace --cpu-resource ${BUILDER_CPU} --memory-resource ${BUILDER_MEM} --privileged \
    --timeout ${BUILDER_TIMEOUT} --node-selector "os.architecture=amd64" --node-selector "copr=${BUILDER_TYPE}" \
    --secret ${BUILDER_SECRET}  --additional-volume-size ${BUILDER_DISK_SIZE} --additional-volume-class ${BUILDER_PVC_NAME}  --additional-volume-mount-path ${BUILDER_PVC_PATH} \
    --additional-pvc-labels ${BUILDER_PVC_LABEL0}